### ISSUE TITLE
3.0 업데이트 TODO

### ISSUE THREAD

**Issue by So-chiru** [So-chiru/llct#163]
- [x] Actions Store localStorage 데이터 저장 wrapper 구현
- [x] 플레이어 Class 구현
- [x] 설정 페이지 hook 구현
- [x] 플레이리스트 구현 (#166)
- [x] 최근 재생 목록 구현
- [ ] 검색 기능 구현 #172 
- [x] 사이트 최적화

**Comment by Gyuni** [comment]
안녕하세요!
UI 디자인 관련하여 몇 가지 건의드리고 싶은 것이 있어 코멘트 남깁니다.


사실 디자인이란 것이 개인의 취향이 많이 반영되기 때문에
제가 건의드리는 디자인이 사이트의 전반적인 컨셉과 맞지 않을 수 있어 조심스럽네요 ㅎㅎ...

괜찮으시다면 아래 링크 확인 한 번 부탁드립니다!
https://www.figma.com/file/Y7Ufk0J7PW0AJ68kbnj1f7/Untitled?node-id=0%3A1


사이트가 계속해서 바뀌어가고 있어 항상 즐거운 마음에 잘 구경하고 있습니다.
감사합니다.

**Comment by So-chiru** [comment]
앗, 디자인 건의 주셔서 감사합니다...!

일단 첫 번째로 배경 색상 수정안은 다른 문제 없이 좋은 것 같습니다. 지금 사이트에 적용된 사항은 외부 라이브러리를 사용해서 앨범 커버의 색을 제대로 뽑지 못하는 감이 없지 않아 있는데, (https://github.com/So-chiru/llct-server/blob/master/route/color.go#L89, https://api.lovelivec.kr/color/11)
알고리즘이 조금 더 깔끔해지면 그때 페이지 색상에 함께 적용해 볼 수 있도록 하겠습니다!

두 번째로, 아티스트 이름이 명시적으로 보이게 할 것이냐 안 할 것이냐에 대한 부분에 대해서는 저도 어느 편이 좋을지 확신이 서지 않아서 마음대로 정해놨는데 아무래도 텍스트로 명확히 표기하는 편이 나을 것 같네요.

건의 주신 Figma 내용의 카드 (모바일 버전, $width < 1000px) 버전은 그대로 적용하겠습니다. 그런데 1000px 이상에서 보이는 카드 내용은 살짝 달라져서

![Screen Shot 2021-04-26 at 9 59 59 PM](https://user-images.githubusercontent.com/32066651/116086427-c69a1480-a6da-11eb-8b20-f03e837f81b9.png)

위와 같이 보이게 되는데 이때 아티스트 이름이 어느 위치에 들어가면 좋을지 확신이 안 서네요. 좋은 아이디어 있으시면 제안 부탁드립니다.

세 번째로, 실제 사이트에서는 건의 주신 내용처럼 간격이 넓게 (브라우저 기본) 적용되어 있는데, 디자인은 저렇게 좁게 되어 있네요. Figma 페이지 내용을 수정하도록 하겠습니다!

기타로 알려주신 카드 간격은 현재 10px로 고정되어 적용되어 있습니다!

항상 사이트에 관심 가져주시니 감사할 따름입니다... 앞으로도 잘 부탁드립니다!

**Comment by Gyuni** [comment]
<img width="1705" alt="스크린샷 2021-04-27 오후 7 59 36" src="https://user-images.githubusercontent.com/54972653/116230893-20f6ac00-a793-11eb-9163-faabd4c4ae79.png">

현재 CSS 설정을 보니 제목이 길어지면 해당 row의 카드 height가 전부 길어지는 것 같은데 만약 height를 고정하는 방식으로 바꾸신다면 이런건 어떨까요? 

아티스트 이름까지 명시적으로 표기하게 되면 가끔 엄청 긴 아티스트 명이 나오는데 (예: 오모히토) 이때도 height가 길어지게 된다면 미관상 좋지 못할 것 같아서 고정하는 방식이 어떨까 싶긴 하네용... 

어떤 이상한 값이 들어올지 모르니 Best를 고려하기 보단 Worst를 고려하려면 이게 제일 무난하지 않을까 싶습니다

**Comment by So-chiru** [comment]
search feature tracks at #172.
